/** cf:http://cf.qq.com/index.shtml
*   by:xylonhuang
*   date:2009-05-20
*   Download by http://sc.xueit.com
**/
var DDSPEED=6;var DDTIMER=15;function ddMenu(id,d){var h=$(id+'-ddheader');var c=$(id+'-ddcontent');clearInterval(c.timer);if(d==1){clearTimeout(h.timer);if(c.maxh&&c.maxh<=c.offsetHeight){return}else if(!c.maxh){c.style.display='block';c.style.height='auto';c.maxh=c.offsetHeight;c.style.height='0px'}c.timer=setInterval(function(){ddSlide(c,1)},DDTIMER)}else{h.timer=setTimeout(function(){ddCollapse(c)},50)}}function ddCollapse(c){c.timer=setInterval(function(){ddSlide(c,-1)},DDTIMER)}function cancelHide(id){var h=$(id+'-ddheader');var c=$(id+'-ddcontent');clearTimeout(h.timer);clearInterval(c.timer);if(c.offsetHeight<c.maxh){c.timer=setInterval(function(){ddSlide(c,1)},DDTIMER)}}function ddSlide(c,d){var currh=c.offsetHeight;var dist;if(d==1){dist=(Math.round((c.maxh-currh)/DDSPEED))}else{dist=(Math.round(currh/DDSPEED))}if(dist<=1&&d==1){dist=1}c.style.height=currh+(dist*d)+'px';c.style.opacity=currh/c.maxh;c.style.filter='alpha(opacity='+(currh*100/c.maxh)+')';if((currh<2&&d!=1)||(currh>(c.maxh-2)&&d==1)){clearInterval(c.timer);currh=null;dist=null}if((d==-1)&&(currh<=4)){clearInterval(c.timer);currh=null;dist=null}}
(function(){var objNav=$('nav'),arrOneleve=objNav.getElementsByTagName('dt')[0].getElementsByTagName('a'),arrTwoleve=objNav.getElementsByTagName('dd')[0].getElementsByTagName('ul'),intOneleve=arrOneleve.length,objhead=$('one-ddheader'),objcontent=$('one-ddcontent');for(var i=0;i<intOneleve;i++){arrOneleve[i].onmouseover=arrTwoleve[i].onmouseover=function(){for(var j=0;j<intOneleve;j++){if(arrOneleve[j].className=='curr'&&arrTwoleve[j].className=='curr'){arrOneleve[j].className='';arrTwoleve[j].className=''}}$("one"+this.id.substr(3)).className='curr';$("two"+this.id.substr(3)).className='curr'}}objNav.onmouseout=function(){for(var i=0;i<intOneleve;i++){arrOneleve[i].className='';arrTwoleve[i].className=''}};objhead.onmouseover=function(){ddMenu('one',1)};objcontent.onmouseover=function(){cancelHide('one')};objhead.onmouseout=objcontent.onmouseout=function(){ddMenu('one',-1)}})();
function setTabcurr(ele,n){if(!$(ele)){return false}var objWrap=$(ele),arrTabs=objWrap.getElementsByTagName('li'),intTabslength=arrTabs.length;if(!arrTabs[n]){n=0}for(var i=0;i<intTabslength;i++){arrTabs[i].className=''}if(n){if(n<intTabslength&&n>=0){arrTabs[n].className='curr'}}else{arrTabs[0].className='curr'}}
function insertFlash(elm,eleid,url,w,h){if(!document.getElementById(elm))return;var str='';str+='<object width="'+w+'" height="'+h+'" id="'+eleid+'" classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=8,0,0,0">';str+='<param name="movie" value="'+url+'" />';str+='<param name="allowScriptAccess" value="always" />';str+='<param name="wmode" value="transparent" />';str+='<param name="quality" value="autohigh" />';str+='<embed width="'+w+'" height="'+h+'" name="'+eleid+'" src="'+url+'" quality="autohigh" swLiveConnect="always" wmode="transparent" allowScriptAccess="always" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>';str+='</object>';document.getElementById(elm).innerHTML=str}
function getUrlparm(){var _anchor="";var _paramStr=new String(window.location.href);var _sharpPos=_paramStr.indexOf("?");if(_sharpPos>=0&&_sharpPos<_paramStr.length-1){_paramStr=_paramStr.substring(_sharpPos+1,_paramStr.length)}else{_paramStr=""}if(_paramStr.length>0){var _paramArr=_paramStr.split("&");if(_paramArr.length>0){var _paramKeyVal=_paramArr[0].split("=");if(_paramKeyVal.length>0){_anchor=_paramKeyVal[1]}}}if(_anchor!=""){return _paramStr}}
function attach(d,a,c,b){if(d.addEventListener){d.addEventListener(a,c,b)}else{if(d.attachEvent){d.attachEvent("on"+a,c)}}}
(function(){if($('logined') && $('unlogin')){CheckLogin();}})();
(function(){QqGg_ShowTypeNew(10, 180, "h180", "i180"); QqGg_ShowTypeNew(10, 181, "h181", "i181");})();
(function(){var objFloat=$('right_gg_box');if(!objFloat){return false}objFloat.innerHTML="<a href='http://cf.qq.com/act/a20081010team/static_icon.htm' target='_blank'><img src='http://ossweb-img.qq.com/images/cf/web200905/r_gg.jpg' /></a>";var intPageHeight=function(){var yScroll;if(window.innerHeight&&window.scrollMaxY){yScroll=window.innerHeight+window.scrollMaxY}else if(document.body.scrollHeight>document.body.offsetHeight){yScroll=document.body.scrollHeight}else{yScroll=document.body.offsetHeight}return yScroll;};objFloat.style.position="absolute";attach(window,"scroll",function(){var iScrollTop=document.body.scrollTop||document.documentElement.scrollTop;if(iScrollTop<parseInt(intPageHeight()-750)){objFloat.style.top=iScrollTop+'px'}})})();/*  |xGv00|7d2c60e3b33f1aab0675667c79910d28 */